// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Winterhold_College_Course_Registration_System.Data;

#nullable disable

namespace Winterhold_College_Course_Registration_System.Migrations
{
    [DbContext(typeof(CollegeDbContext))]
    [Migration("20260327101907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "ALT-101",
                            CourseName = "Foundations of Matter",
                            Credits = 2,
                            Department = "Alteration",
                            Description = "Introduction to manipulating physical reality through Alteration magic.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "ALT-201",
                            CourseName = "Flesh Spells and Warding",
                            Credits = 3,
                            Department = "Alteration",
                            Description = "Defensive Alteration techniques including Oakflesh and Stoneflesh.",
                            GradeLevel = "Apprentice",
                            IsActive = true,
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "ALT-401",
                            CourseName = "Paralysis and Transmutation",
                            Credits = 5,
                            Department = "Alteration",
                            Description = "Advanced transmutation and paralysis spells for seasoned mages.",
                            GradeLevel = "Expert",
                            IsActive = true,
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "DES-101",
                            CourseName = "Elemental Theory",
                            Credits = 2,
                            Department = "Destruction",
                            Description = "Understanding fire, frost, and shock as magical forces.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "DES-201",
                            CourseName = "Flame and Frost Casting",
                            Credits = 3,
                            Department = "Destruction",
                            Description = "Practical casting of Flames, Frostbite, and Sparks.",
                            GradeLevel = "Apprentice",
                            IsActive = true,
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseCode = "DES-501",
                            CourseName = "Incineration Arts",
                            Credits = 6,
                            Department = "Destruction",
                            Description = "Master-level Destruction magic. Firestorm, Blizzard, Thunder.",
                            GradeLevel = "Master",
                            IsActive = true,
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseCode = "ILL-101",
                            CourseName = "The Quiet Mind",
                            Credits = 2,
                            Department = "Illusion",
                            Description = "Introduction to mind-affecting magic and the theory of illusion.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseCode = "ILL-301",
                            CourseName = "Invisibility and Muffle",
                            Credits = 4,
                            Department = "Illusion",
                            Description = "Concealment spells and sensory manipulation.",
                            GradeLevel = "Adept",
                            IsActive = true,
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseCode = "RES-101",
                            CourseName = "Healing Fundamentals",
                            Credits = 2,
                            Department = "Restoration",
                            Description = "Basic healing spells, ward theory, and the ethics of Restoration.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseCode = "RES-301",
                            CourseName = "Ward Mastery",
                            Credits = 4,
                            Department = "Restoration",
                            Description = "Advanced ward spells and magical resistance techniques.",
                            GradeLevel = "Adept",
                            IsActive = true,
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 11,
                            CourseCode = "CON-101",
                            CourseName = "Planes of Oblivion",
                            Credits = 2,
                            Department = "Conjuration",
                            Description = "Survey of Daedric realms and the theory of conjuration.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 12,
                            CourseCode = "CON-201",
                            CourseName = "Summoning Familiars",
                            Credits = 3,
                            Department = "Conjuration",
                            Description = "Practical summoning of Atronachs and bound weapons.",
                            GradeLevel = "Apprentice",
                            IsActive = true,
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 13,
                            CourseCode = "ENC-101",
                            CourseName = "Soul Gems and Essences",
                            Credits = 2,
                            Department = "Enchanting",
                            Description = "Introduction to soul gems, soul trapping, and magical essences.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 6
                        },
                        new
                        {
                            Id = 14,
                            CourseCode = "ENC-301",
                            CourseName = "Weapon Enchantment",
                            Credits = 4,
                            Department = "Enchanting",
                            Description = "Imbuing weapons with elemental and utility enchantments.",
                            GradeLevel = "Adept",
                            IsActive = true,
                            ProfessorId = 6
                        },
                        new
                        {
                            Id = 15,
                            CourseCode = "MYS-201",
                            CourseName = "Magical Theory",
                            Credits = 3,
                            Department = "Mysticism",
                            Description = "The study of magic as a fundamental force of the universe.",
                            GradeLevel = "Apprentice",
                            IsActive = true,
                            ProfessorId = 10
                        },
                        new
                        {
                            Id = 16,
                            CourseCode = "MYS-401",
                            CourseName = "Telekinesis and Detection",
                            Credits = 5,
                            Department = "Mysticism",
                            Description = "Advanced applications of Mysticism in field and laboratory.",
                            GradeLevel = "Expert",
                            IsActive = true,
                            ProfessorId = 10
                        },
                        new
                        {
                            Id = 17,
                            CourseCode = "MGT-101",
                            CourseName = "College History and Lore",
                            Credits = 2,
                            Department = "Management",
                            Description = "Survey of the College's history from the First Era to the present.",
                            GradeLevel = "Novice",
                            IsActive = true,
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 18,
                            CourseCode = "MGT-201",
                            CourseName = "Arcane Administration",
                            Credits = 3,
                            Department = "Management",
                            Description = "Managing magical institutions, resources, and student records.",
                            GradeLevel = "Apprentice",
                            IsActive = true,
                            ProfessorId = 8
                        });
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(180, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Alteration",
                            HireDate = new DateTime(4150, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tolfdir",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(220, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Destruction",
                            HireDate = new DateTime(4160, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Faralda",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(250, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Illusion",
                            HireDate = new DateTime(4155, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drevis Neloren",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(270, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Restoration",
                            HireDate = new DateTime(4165, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colette Marence",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(200, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Conjuration",
                            HireDate = new DateTime(4158, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phinis Gestor",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(260, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Enchanting",
                            HireDate = new DateTime(4162, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sergius Turrianus",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(150, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireDate = new DateTime(4140, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Savos Aren",
                            Role = "Archmage"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(240, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Restoration",
                            HireDate = new DateTime(4168, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mirabelle Ervine",
                            Role = "Assistant"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(210, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireDate = new DateTime(4152, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urag gro-Shub",
                            Role = "Librarian"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(280, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Mysticism",
                            HireDate = new DateTime(4170, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arniel Gane",
                            Role = "Assistant"
                        });
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Major")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Course", b =>
                {
                    b.HasOne("Winterhold_College_Course_Registration_System.Models.Staff", "Professor")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Enrollment", b =>
                {
                    b.HasOne("Winterhold_College_Course_Registration_System.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Winterhold_College_Course_Registration_System.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Staff", b =>
                {
                    b.Navigation("CoursesTaught");
                });

            modelBuilder.Entity("Winterhold_College_Course_Registration_System.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
